export const CARD_LOCATION = [
	{
		id: 1,
		img: 'cardLocation/cardLocation.jpg',
		address: 'Минск, б-р Мулявина, д. 10',
		price: '65.00 BYN',
		priceTime: 'за сутки',
		rooms: '4 комн.',
		numberPeopleRoom: '4 (2+2)',
		label: 'gold',
		area: 'Шабаны',
		metro: 'Грушевка',
		quadrature: '179 м²',
		owner: {
			img: 'cardLocation/user.png',
			title: 'Владелец',
			name: 'Dmitriy',
			email: 'vladimir6234@tut.by',
			tel: ' +375 (29) 291-14-44',
			socials: [
				{ social: 'viber', href: '#' },
				{ social: 'whatsApp', href: '#' },
				{ social: 'mail', href: '#' },
			],
		},
		description:
			'Какое-то описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание ...',
	},
	{
		id: 2,
		img: 'cardLocation/cardLocation2.jpg',
		address: 'Минск, б-р Мулявина, д. 10',
		price: '65.00 BYN',
		priceTime: 'за сутки',
		rooms: '4 комн.',
		numberPeopleRoom: '4 (2+2)',
		label: 'gold',
		area: 'Шабаны',
		metro: 'Грушевка',
		quadrature: '179 м²',
		owner: {
			img: 'cardLocation/user.png',
			title: 'Владелец',
			name: 'Dmitriy',
			email: 'vladimir6234@tut.by',
			tel: ' +375 (29) 291-14-44',
			socials: [
				{ social: 'viber', href: '#' },
				{ social: 'whatsApp', href: '#' },
				{ social: 'mail', href: '#' },
			],
		},
		description:
			'Какое-то описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание ...',
	},
	{
		id: 3,
		img: 'cardLocation/cardLocation.jpg',
		address: 'Минск, б-р Мулявина, д. 10',
		price: '65.00 BYN',
		priceTime: 'за сутки',
		rooms: '4 комн.',
		numberPeopleRoom: '4 (2+2)',
		label: 'gold',
		area: 'Шабаны',
		metro: 'Грушевка',
		quadrature: '179 м²',
		owner: {
			img: 'cardLocation/user.png',
			title: 'Владелец',
			name: 'Dmitriy',
			email: 'vladimir6234@tut.by',
			tel: ' +375 (29) 291-14-44',
			socials: [
				{ social: 'viber', href: '#' },
				{ social: 'whatsApp', href: '#' },
				{ social: 'mail', href: '#' },
			],
		},
		description:
			'Какое-то описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание ...',
	},
	{
		id: 4,
		img: 'cardLocation/cardLocation2.jpg',
		address: 'Минск, б-р Мулявина, д. 10',
		price: '65.00 BYN',
		priceTime: 'за сутки',
		rooms: '4 комн.',
		numberPeopleRoom: '4 (2+2)',
		label: 'gold',
		area: 'Шабаны',
		metro: 'Грушевка',
		quadrature: '179 м²',
		owner: {
			img: 'cardLocation/user.png',
			title: 'Владелец',
			name: 'Dmitriy',
			email: 'vladimir6234@tut.by',
			tel: ' +375 (29) 291-14-44',
			socials: [
				{ social: 'viber', href: '#' },
				{ social: 'whatsApp', href: '#' },
				{ social: 'mail', href: '#' },
			],
		},
		description:
			'Какое-то описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание ...',
	},
	{
		id: 5,
		img: 'cardLocation/cardLocation2.jpg',
		address: 'Минск, б-р Мулявина, д. 10',
		price: '65.00 BYN',
		priceTime: 'за сутки',
		rooms: '4 комн.',
		numberPeopleRoom: '4 (2+2)',
		label: 'gold',
		area: 'Шабаны',
		metro: 'Грушевка',
		quadrature: '179 м²',
		owner: {
			img: 'cardLocation/user.png',
			title: 'Владелец',
			name: 'Dmitriy',
			email: 'vladimir6234@tut.by',
			tel: ' +375 (29) 291-14-44',
			socials: [
				{ social: 'viber', href: '#' },
				{ social: 'whatsApp', href: '#' },
				{ social: 'mail', href: '#' },
			],
		},
		description:
			'Какое-то описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание ...',
	},
	{
		id: 6,
		img: 'cardLocation/cardLocation.jpg',
		address: 'Минск, б-р Мулявина, д. 10',
		price: '65.00 BYN',
		priceTime: 'за сутки',
		rooms: '4 комн.',
		numberPeopleRoom: '4 (2+2)',
		label: 'gold',
		area: 'Шабаны',
		metro: 'Грушевка',
		quadrature: '179 м²',
		owner: {
			img: 'cardLocation/user.png',
			title: 'Владелец',
			name: 'Dmitriy',
			email: 'vladimir6234@tut.by',
			tel: ' +375 (29) 291-14-44',
			socials: [
				{ social: 'viber', href: '#' },
				{ social: 'whatsApp', href: '#' },
				{ social: 'mail', href: '#' },
			],
		},
		description:
			'Какое-то описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание квартиры, описание ...',
	},
]
